# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-164034139-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/gstaxy'}
- {icon: 'twitter', link: 'https://twitter.com/slevanature'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/gslevantremblay/'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Guillaume_Slevan-Tremblay'}
- {icon: 'rss-square', link: '/feed.xml'}
#- {icon: 'rss-square', link: '/rss-feed.xml'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
